export type homePage = {
  _id: string;
  _createdAt: Date;
  name: string;
  slug: string;
  heroText: string;
  introText: string;
  introSubText: string;
  featuresTitle: string;
  featuresHeader1: string;
  featuresText1: string;
  featuresHeader2: string;
  featuresText2: string;
  featuresHeader3: string;
  featuresText3: string;
  featuresHeader4: string;
  featuresText4: string;
  featuresHeader5: string;
  featuresText5: string;
  featuresHeader6: string;
  featuresText6: string;
  priceTextBasic: string;
  priceTextEssential: string;
  priceTextPremium: string;
};
